
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel.ModelInput sampleData = new MLModel.ModelInput()
            {
                Calories_eat_change = 1661F,
                Calorie_for_KG = 347F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Weekly_weight_change with predicted Weekly_weight_change from sample data...\n\n");


            Console.WriteLine($"Calories_eat_change: {sampleData.Calories_eat_change}");
            Console.WriteLine($"Calorie_for_KG: {sampleData.Calorie_for_KG}");


            Console.WriteLine($"\n\nPredicted Weekly_weight_change: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
