// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HealthProgramML.Model
{
    public class ModelInput
    {
        [ColumnName("calories"), LoadColumn(0)]
        public float Calories { get; set; }


        [ColumnName("weight"), LoadColumn(1)]
        public float Weight { get; set; }


    }
}
